spring:
  datasource:
    url: jdbc:mysql://13.124.69.97:3306/steady
    username: steadydev
    password: steady13dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true

oauth:
  kakao:
    client-id: b43ec3ba4cc2a54d31c6c1f7315c142b
    client-secret: VqHpq8lJMHFX0grjyFYAAzZ4mkGnHJHv
    redirect-uri: https://steadies.kr/
    response-type: code

jwt:
  secret_key: ff799404c98d2fa8832a876d456eb729e39e190f9a6377ca1ffe396b000512ed4b76c850fc8cd3c2f010f04bc992eba4cec593ffb2d5d8e385701bbb2fd7bc12
  access_token_expiration: 86400000
  refresh_token_expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  tomcat:
    mbeanregistry:
      enabled: true

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access_key: 123123213wdsdadasd
      secret_key: I5+fvONYwIYiEaAJxo9NWuasdasdasdasdasdsda
  s3:
    bucket: team-13-image-bucket
